### PR TITLE
Optimize the splitting of XPath unions

### PR DESCRIPTION
**Pull request by stof**
Consuming each char of the XPath string one by one is slower than necessary, as only a few chars are interesting for us.
This implementation written by @nicolas-grekas for Symfony BrowserKit in https://github.com/symfony/symfony/pull/20235 (and slightly adapted for our needs) is much faster by consuming irrelevant chars in batch.

See https://gist.github.com/stof/5131c79c576600800aac7313b182d44d for the benchmark:
- the (broken) Mink 1.7 implementation is the `regex` one
- the implementation merged in #720 is the `iteration`
- the implementation submitted in this PR is the `grekas_checking` one

Note that I added additional comments compared to the code written by Nicolas to explain what actually happens.

### CODE REVIEW

**Comment by stof** [comment]
@klausi sorry that your first contribution to Mink will mostly be replaced after a few days only. I hope your next contribution will last longer...

**Comment by aik099** [comment]
Looking at the code alone should be quite performant. Luckily we have unit tests in place to confirm, that xpath processing wasn't broken as a result.

**Comment by stof** [comment]
@aik099 for performance, you can also look at the benchmark (the gist also contains results if you scroll)

**Comment by klausi** [comment]
@stof no worries, I'm just happy that we got it all fixed so quickly.

I can confirm that the change in this PR does not break in Drupal and behaves the same.

**Pull request merged**
