### PR TITLE
Auto-start session only upon 1st "->visit(...)" method call

### LINKED ISSUE #678: Auto-start session on "->visit(...)" call
Currently if somebody attempts to do a `$session->visit(...);` call without calling `$session->start()` upfront, then this will ends up in exception.

To help out users I propose to auto-start session (only if not started already) inside `$session->visit(...)` method before any existing code.

### PR DESCRIPTION
**Pull request by aik099**
Closes #678

### CODE REVIEW

**Comment by aik099** [comment]
@stof , any updates on this?

**Comment by stof** [comment]
There is a difference now: ``assertSession()`` may be called for a non-started session, while it was starting it previously. Should we force starting ? It would match the previous behavior, but I'm not sure it is necessary. The assertions are not usable without visiting a page anyway.

**Comment by aik099** [comment]
None of `WebAssert` class methods are calling `visit` internally. I suppose the `WebAssert` class is used something like this:

```php
$session = ...;// obtain session somehow
$session->visit('page_url');
$assert = $mink->assertSession($session);
$assert->assert...
```
If that is the case, then no changes should be made to `Mink::assertSession` because the started session won't be usable anyway without visiting a page even though technically it's a BC break.

**Comment by stof** [comment]
yeah, even though it is technically a BC break, it is only breaking BC for unsupported usages of the API. So fine.

**Pull request merged**
